name: bidrag-aktoerregister
dbinstancename: bidrag-aktoerregister
dbname: bidrag-aktoerregister-db
ingresses:
  - https://bidrag-aktoerregister.nav.no/
env:
  SPRING_PROFILES_ACTIVE: prod
  BIDRAG_PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  BIDRAG_PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  BIDRAG_SAMHANDLER_URL: https://bidrag-samhandler.intern.nav.no
  BIDRAG_SAMHANDLER_SCOPE: prod-gcp.bidrag.bidrag-samhandler