NAIS_APP_NAME: bidrag-aktoerregister

# Azure
AZURE_APP_CLIENT_ID: b683404e-331a-4da2-959c-90d430228648
# AZURE_APP_CLIENT_ID: <CLIENT_ID>
AZURE_APP_CLIENT_SECRET: gth8Q~S3ZqIv~6ksGqaQyw~gAUr4JQIJDH1R.deE
# AZURE_APP_CLIENT_SECRET: <CLIENT_SECRET>
AZURE_APP_TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

# DB
spring:
  jpa:
    database: POSTGRESQL
DB_HOST: localhost
DB_PORT: '5432'
DB_DATABASE: test_db
DB_USERNAME: cloudsqliamuser
DB_PASSWORD: root

# URL
BIDRAG_SAMHANDLER_URL: https://bidrag-samhandler-feature.dev.intern.nav.no
BIDRAG_SAMHANDLER_SCOPE: dev-gcp.bidrag.bidrag-samhandler-feature

BIDRAG_PERSON_URL: https://bidrag-person-feature.dev.intern.nav.no/bidrag-person
BIDRAG_PERSON_SCOPE: dev-fss.bidrag.bidrag-person-feature

# MQ
MQ_QUEUE_MANAGER: QM1
MQ_TPS_REQUEST_QUEUE: DEV.QUEUE.1
MQ_PORT: '1414'
MQ_USERNAME: app
MQ_PASSWORD: passw0rd
MQ_CHANNEL: DEV.APP.SVRCONN
MQ_APPLICATION_NAME: bidrag-aktorregister
MQ_TIMEOUT: '15000'
MQ_TPS_EVENT_QUEUE: DEV.QUEUE.1
MQ_HOST: host.docker.internal
MQ_TSS_REQUEST_QUEUE: DEV.QUEUE.1

# Maskinporten
MASKINPORTEN_WELL_KNOWN_URL: https://test.maskinporten.no/.well-known/oauth-authorization-server

# Logging
logging:
  config: src/main/resources/logback-local.xml