#TSS MQ config

# If running in docker
mq.host = host.docker.internal

# If running directly on host
# mq.host = localhost

mq.port = 1414
mq.channel = DEV.APP.SVRCONN
mq.queueManager = QM1
mq.username = app
mq.password = passw0rd
mq.tssRequestQueue = DEV.QUEUE.1
mq.tpsRequestQueue = ?
mq.timeout = 15000
mq.applicationName = bidrag-aktorregister


MASKINPORTEN_WELL_KNOWN_URL=https://ver2.maskinporten.no/.well-known/oauth-authorization-server