server.servlet.context-path=/bidrag-aktoerregister
server.port=8080

springdoc.swagger-ui.path=/

no.nav.security.jwt.issuer.maskinporten.discovery-url=${MASKINPORTEN_WELL_KNOWN_URL:https://ver2.maskinporten.no/.well-known/oauth-authorization-server}
no.nav.security.jwt.issuer.maskinporten.validation.optional-claims=sub,aud,nbf
