#TSS MQ config
mq.host = b27apvl220.preprod.local
mq.port = 1413
mq.channel = Q1_BIDRAG_AKTORREGIS
mq.queueManager = MQLS02
mq.username = srvbidrag-aktorregis
mq.password = {MQ_PASSWORD}
mq.tssRequestQueue = queue:///QA.Q1_415.AS10_SAMHANDLER_SERVICE?targetClient=1
mq.tpsRequestQueue = queue:///QA.Q1_411.TPS_FORESPORSEL_XML_O?targetClient=1
mq.tpsEventQueue = QA.Q1_BIDRAG_AKTORREGIS.TPSDISTRIBUSJON
mq.timeout = 15000
mq.applicationName = bidrag-aktorregister


# Database config
spring.jpa.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.schema=aktoerregister
spring.datasource.hikari.minimum-idle=6
spring.datasource.hikari.maximum-pool-size=6