#TSS MQ config
mq.host = b27apvl220.preprod.local
mq.port = 1413
mq.channel = Q1_BIDRAG_AKTORREGIS
mq.queueManager = MQLS02
mq.username = srvbidrag-aktorregis
mq.password = {MQ_PASSWORD}
mq.queueName = QA.Q1_415.AS10_SAMHANDLER_SERVICE
mq.timeout = 15000
mq.applicationName = bidrag-aktorregister