server.servlet.context-path=/bidrag-aktoerregister
server.port=8080

springdoc.swagger-ui.path=/

no.nav.security.jwt.issuer.maskinporten.discovery-url=${MASKINPORTEN_WELL_KNOWN_URL}
no.nav.security.jwt.issuer.maskinporten.validation.optional-claims=sub,aud,nbf
